-- CreateTable
CREATE TABLE "Token" (
    "uId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "expiry" DATETIME NOT NULL,
    CONSTRAINT "Token_uId_fkey" FOREIGN KEY ("uId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
